import type { Pin } from "./types";

const photo = (label: string) =>
  `https://placehold.co/400x300?text=${encodeURIComponent(label)}`;

export const initialPins: Pin[] = [
  {
    id: "pin-1",
    floorId: 1,
    xCoord: 20,
    yCoord: 45,
    level: 1,
    building: "Open Field",
    description: "Uneven ground near the field bleachers.",
    photoUrl: photo("Issue Photo"),
    status: "Approved",
    synced: true,
    reporterName: "Maria Santos",
    reporterSection: "Grade 12 - HUMSS A",
    reporterEmail: "maria.santos@gmail.com",
  },
  {
    id: "pin-2",
    floorId: 1,
    xCoord: 35,
    yCoord: 70,
    level: "Fixed",
    building: "Open Field",
    description: "Cracked pavement near the field entrance repaired.",
    photoUrl: photo("Issue Photo"),
    status: "Approved",
    synced: true,
    reporterName: "Juan Dela Cruz",
    reporterSection: "Grade 11 - STEM B",
    reporterEmail: "juan.delacruz@gmail.com",
  },
  {
    id: "pin-3",
    floorId: 1,
    xCoord: 75,
    yCoord: 30,
    level: 3,
    building: "Senior High School Bldg.",
    description: "Exposed wiring near the 1st floor entrance.",
    photoUrl: photo("Issue Photo"),
    status: "Approved",
    synced: true,
    reporterName: "Angela Reyes",
    reporterSection: "Grade 12 - ABM A",
    reporterEmail: "angela.reyes@gmail.com",
  },
  {
    id: "pin-4",
    floorId: 2,
    xCoord: 80,
    yCoord: 45,
    level: 2,
    building: "Senior High School Bldg.",
    description: "Leaking faucet in the 2nd floor restroom.",
    photoUrl: photo("Issue Photo"),
    status: "Approved",
    synced: true,
    reporterName: "Mark Villanueva",
    reporterSection: "Grade 11 - HUMSS C",
    reporterEmail: "mark.villanueva@gmail.com",
  },
  {
    id: "pin-5",
    floorId: 3,
    xCoord: 70,
    yCoord: 65,
    level: 1,
    building: "Senior High School Bldg.",
    description: "Loose ceiling tile on the 3rd floor hallway.",
    photoUrl: photo("Issue Photo"),
    status: "Approved",
    synced: true,
    reporterName: "Kim Torres",
    reporterSection: "Grade 12 - STEM A",
    reporterEmail: "kim.torres@gmail.com",
  },
  {
    id: "pin-6",
    floorId: 4,
    xCoord: 85,
    yCoord: 75,
    level: "Fixed",
    building: "Senior High School Bldg.",
    description: "Broken ceiling light on the 4th floor replaced.",
    photoUrl: photo("Issue Photo"),
    status: "Approved",
    synced: true,
    reporterName: "Paolo Ramos",
    reporterSection: "Grade 11 - ABM B",
    reporterEmail: "paolo.ramos@gmail.com",
  },
];
